# Generated by Django 3.2.20 on 2023-08-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='type_development',
        ),
    ]
